### ISSUE TITLE
Add psi blades coil and laser

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#13]
Add psi blades to the pack for Laser, Coil tier.
There are no assets use placeholders for now. You will need to set the research requirements, set the engineering costs, and set the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by Anthogator** [comment]
So this issue is canceled, yes?

**Comment by TNychka** [comment]
Issue closed, no longer relevant.
