### ISSUE TITLE
SMGs are not equipable by the loadout screen

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#18]
Bug report from a tester in trello, SMGs are not equipable by the loadout screen. Investigate to verify and fix if necessary. V0.1 of the mod.

**Comment by TNychka** [comment]
Full trello text: It appears that after the first promotion, the SMG appears visible and equippable, however in the beginning with all rookies  it has a limitation. Also, SMG has a clip of 3 instead of 2
Note: I was unable to verify being unable to equip it on soldiers. The clip size is as balanced from JL himself, so that does not need to be fixed.

**Comment by Anthogator** [comment]
I am also unable to verify being unable to equip it on soldiers.

However, I modified the Assault Rifle's clip size to 3 in my most recent pull request, as part of balancing the BR, as per JLPH. So we will need to update SMG clip size as well, down to 2.

**Comment by Anthogator** [comment]
I've updated the SMG clip size

**Comment by TNychka** [comment]
After an investigation, the tech-whitesource team has discovered that whitesource does not scan the package.json by default. This means that all of those dependencies are not tracked by whitesource.

From our security team contact:
"I had a chat with WhiteSource team on this question and they told me that if you are using Jenkins plugin to perform the scan, WhiteSource may not look at package.json for vulnerabilities in dependencies. They are suggesting to instead use npm plugin, http://docs.whitesourcesoftware.com/display/serviceDocs/NPM+Plugin or WhiteSource jar, https://whitesource.atlassian.net/wiki/spaces/WD/pages/33718339/File+System+Agent, to perform scans"

**Comment by TNychka** [comment]
Sorry ignore that, wrong pull request

**Comment by TNychka** [comment]
Closing as not relevant.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SMG's do appear in the game in mission prep, however you cannot "pre-equip" them in the "view soldier" mode.](https://trello.com/c/XbsiQQs6/7-smgs-do-appear-in-the-game-in-mission-prep-however-you-cannot-pre-equip-them-in-the-view-soldier-mode)
