### ISSUE TITLE
Scatterray displays [SHARPSHOOTER UPGRADE] on Engineering UI

### ISSUE THREAD

**Issue by fowlJ** [X2LongWarOfTheChosen/LWOTC_WeaponPack#19]
![scatterray_displaybug](https://user-images.githubusercontent.com/34240003/33674408-64bcf35e-da7d-11e7-8d56-9e1ddaae72da.png)

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/22
