### ISSUE TITLE
Scatterray unlocked with Advanced Laser Weapons

### ISSUE THREAD

**Issue by fowlJ** [X2LongWarOfTheChosen/LWOTC_WeaponPack#20]
In vanilla, shotgun class weapons are unlocked with the primary weapon research that unlocks rifles, not the secondary one that unlocks cannons and sniper rifles.

**Comment by Anthogator** [comment]
I've fixed this in my fork

**Comment by TNychka** [comment]
Closed in https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/22
