### ISSUE TITLE
Weapon Schematic cost assumptions

### ISSUE THREAD

**Issue by Danice123** [X2LongWarOfTheChosen/LWOTC_WeaponPack#25]
Code assumes that schematics will always cost alloys and supplies, but checks if they cost elerium. This should be standardized.

**Comment by Danice123** [comment]
Also replicated in the weapon building code without schematics

**Comment by Anthogator** [comment]
Is there a case where a schematic will not cost alloys or supplies? If not, I'm not sure why this would need to be changed.

**Comment by Danice123** [comment]
The case would be if someone changed the config files to do so.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Weapon Schematic cost assumptions](https://trello.com/c/7VK45n5V/17-weapon-schematic-cost-assumptions)

**Comment by TNychka** [comment]
It should be done as a basic precaution. Won't be too hard and it's a good way to introduce a new team member.

**Comment by Danice123** [comment]
#51
