### ISSUE TITLE
Missing configuration for weapons

### ISSUE THREAD

**Issue by Danice123** [X2LongWarOfTheChosen/LWOTC_WeaponPack#26]
\*\_\*\_TRADINGPOSTVALUE
and
\*\_\*\_IPOINTS
exist but are not implemented.

\*\_LASER_ISUPPLIES
exists but seems to be a stub from wotc's code, so probably could get rid of it?

**Comment by Danice123** [comment]
`Template.PointsToComplete =default.ROCKETLAUNCHER_IPOINTS;`
from the rocket launcher

So I'm not sure what this does and if it should be assigned to main weapons

**Comment by Anthogator** [comment]
Looks like you're right about ISUPPLIES. Those variables aren't referenced throughout the rest of the file, they can be deleted. They exist in other tiers as well.

*_*_TRADINGPOSTVALUE
and
*_*_IPOINTS
should also be added to XComLW_WeaponPack.ini for all LS and CG tier weapons that don't currently have it.

**Comment by Danice123** [comment]
Do we know what PointsToComplete does? I searched in the code and didn't find anything actually using the variable, plus most things set it to zero. Perhaps not necessary

**Comment by Anthogator** [comment]
That's an alternate use of the *_*_RESEARCH_POINTS variable, for use in difficulty tuning. Currently only set for Legend, as far as I can tell.

**Comment by Derseboom** [comment]
Working on this issue right now :P

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing configuration for weapons](https://trello.com/c/VSNMTtGe/16-missing-configuration-for-weapons)

**Comment by TNychka** [comment]
@Derseboom it's yours.

**Comment by Derseboom** [comment]
Added the needed values to all weapons except conventional tier. Also fixed an inconsistency in the Laser Vektor Rifle code; upgrade slot=1, changed to upgrade slot=2.

**Comment by Danice123** [comment]
#43
