### ISSUE TITLE
Bullpup ImagePath not used correctly

### ISSUE THREAD

**Issue by Danice123** [X2LongWarOfTheChosen/LWOTC_WeaponPack#28]
Needs to use image config path

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bullpup ImagePath not used correctly](https://trello.com/c/8um4S4ny/15-bullpup-imagepath-not-used-correctly)

**Comment by Danice123** [comment]
#47

**Comment by TNychka** [comment]
Completed in Assorted bug fixes #47
