### ISSUE TITLE
Add battle rifles to pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#3]
Add battle rifles to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by Anthogator** [comment]
Dibs

**Comment by TNychka** [comment]
Alright, it's all yours

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/22
