### ISSUE TITLE
int file contents missing

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#32]
After various merge conflicts the int content has gone missing.

**Comment by Anthogator** [comment]
Could this be solved by simply reuploading the .int files? I still have them and can do that if so.

**Comment by TNychka** [comment]
Yeah reuploading will do it. 
Make sure (if possible) that it has the content for BRs, MRs, Vektors and bullpups

**Comment by TNychka** [comment]
Fixed in https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/33
