### ISSUE TITLE
Marksman Rifles do not have the Fire Weapon ability

### ISSUE THREAD

**Issue by Anthogator** [X2LongWarOfTheChosen/LWOTC_WeaponPack#34]
They are capable of entering Overwatch, and shooting while in Overwatch, but I can't get the regular shot ability to work for the life of me.

**Comment by TNychka** [comment]
Is this the latest build on dev?

**Comment by Anthogator** [comment]
Yes

**Comment by TNychka** [comment]
Thought I fixed it, maybe not. Previously they used the sniper_rifle standard shot which is probably the shooting issue. whoever takes this ticket should investigate further

**Comment by Anthogator** [comment]
I should clarify - the Conventional MR works just fine and dandy. It can shoot all day long. It only worked that way when I added the SniperStandardFire ability and reduced typical action cost to 1.

This method doesn't seem to work above CV tier. Neither does using a standard shot, with or without the typical action cost reduction.

I've also tried using SniperStandardShot instead of SniperStandardFire. Both seem to work for CV, iirc. Neither seems to work above CV.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Marksman Rifles do not have the Fire Weapon ability #34](https://trello.com/c/7wUrZWZn/13-marksman-rifles-do-not-have-the-fire-weapon-ability-34)

**Comment by Anthogator** [comment]
Actually, now that I'm testing this again, it looks like you did fix it.

**Comment by TNychka** [comment]
Lol nice. Closing issue as fixed in https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/31
