### ISSUE TITLE
Plasma Marksman Rifle needs 5 tile squadsight

### ISSUE THREAD

**Issue by Anthogator** [X2LongWarOfTheChosen/LWOTC_WeaponPack#35]
This looks like it will be incredibly complex to accomplish - squadsight as it is looks very complex and I don't see any easy way to limit its range.

**Comment by TNychka** [comment]
Might need to add a plasma ability to the MR similar to the SMG. Are you working on this?

**Comment by Anthogator** [comment]
"a plasma ability to the MR similar to the SMG" I'm not sure I understand this. The SMG does not currently have a plasma ability.

**Comment by TNychka** [comment]
Ah sorry, I mean the SMG have a set bunch of abilities used to modify the mobility of the actor using the weapon. If we can add an ability to the Marksman rifle for beam tier (what I meant by plasma, I'm still stuck in EW) that will most likely fix it.

**Comment by Anthogator** [comment]
Ah, yes. It will need its own X2Ability, similar to what the SMG and BR have. That part's the easy part, imo. But limiting the Squadsight effect to be only 5 tiles is the part I do not know how to do.

**Comment by TNychka** [comment]
Goodluck! :smile:

**Comment by TNychka** [comment]
Also if you do work on this put it in a unique PR
