### ISSUE TITLE
Coil tier weapons have pierce not shred

### ISSUE THREAD

**Issue by Danice123** [X2LongWarOfTheChosen/LWOTC_WeaponPack#38]
Still in debate I think

Probably should add pierce to mag weapons with this change

**Comment by TNychka** [comment]
I think the final decision was to keep it pierce.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing configuration for weapons](https://trello.com/c/VSNMTtGe/16-missing-configuration-for-weapons)
