### ISSUE TITLE
Add Carbines to the weapons pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#4]
Add carbines to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by KnowingNova** [comment]
I will do this

**Comment by TNychka** [comment]
It's yours

**Comment by Danice123** [comment]
#46
