### ISSUE TITLE
Correctly balance Templar Autopistols, Reaper Vektors and Spark Spark Rifles

### ISSUE THREAD

**Issue by Danice123** [X2LongWarOfTheChosen/LWOTC_WeaponPack#41]
ini changes

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Correctly balance Templar Autopistols, Reaper Vektors and Spark Spark Rifles](https://trello.com/c/S80gp93t/14-correctly-balance-templar-autopistols-reaper-vektors-and-spark-spark-rifles)

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/40
