### ISSUE TITLE
Laser Marksman rifles have burst fire

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#49]
It'll be up to vortex to create the new firing animation if necessary. Who ever takes this ticket will need to 
1. Check if the laser long rifle also has burst
2. If it doesn't let vortex know and she can grab the assets from there
3. When that's done upload the new asset and confirm it's working.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Laser Marksman rifles have burst fire.](https://trello.com/c/6LWcVje0/14-laser-marksman-rifles-have-burst-fire)

**Comment by Danice123** [comment]
#52
