### ISSUE TITLE
Add hunting shotgun to the pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#5]
Note: Documentation is sparse on this weapon. Part of this task should be to put all information in the final document below.
Note: Assets do not exist for this weapon. You will need to use a placeholder for the time being.
Add hunting shotgun to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by KnowingNova** [comment]
I will do this

**Comment by TNychka** [comment]
All yours

**Comment by TNychka** [comment]
Hey @BibiFloris while you figure out the carbines, I'm going to let someone else start work on this

**Comment by Danice123** [comment]
I was considering picking this up

**Comment by TNychka** [comment]
If you want it it's yours. We have zero assets for this weapon

**Comment by TNychka** [comment]
Trello issue https://trello.com/c/FIrsLAjd

**Comment by Danice123** [comment]
Retire this issue?

**Comment by TNychka** [comment]
Put it on hold for now

**Comment by TNychka** [comment]
Hunting shotgun not added
