### ISSUE TITLE
Asset Upload issues

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#50]
Looks like not all of the UPK assets made it into the pack. This task will be gathering and confirming that all of the current assets appear in the game.

**Comment by TNychka** [comment]
https://trello.com/c/xc7SuuY7

**Comment by Anthogator** [comment]
Which assets are currently reported as missing?

**Comment by TNychka** [comment]
From what I saw just the marksman, battle rifle, but I haven't gotten through everything yet

**Comment by Danice123** [comment]
BRPack assets

**Comment by Anthogator** [comment]
I will see if I can reupload these tonight or tomorow then.

**Comment by Anthogator** [comment]
All the upk files I have for the BR and MR are in the repo. There are only 5, all in the LWBRMRPack folder. However, none of them seem to be listed in LWOTC_WeaponPack.x2proj

Could this be the issue?

**Comment by TNychka** [comment]
I don't think so, I think the issue is that they are in a subfolder which isn't properly accessed by the weapons. we need LWBRMRPack.archetypewhatevertheresetishere

**Comment by Danice123** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/commit/07e3dab2fc26e3da1150e54402df9b40441025f2

fixes this
