### ISSUE TITLE
Add Marksman Rifle to weapons pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#6]
Add Marksman Rifle to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by Anthogator** [comment]
Double Dibs

**Comment by TNychka** [comment]
Can't assign right now for some reason, but anthogator is working on this task

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/pull/22
