### ISSUE TITLE
Bad friendly text for laser carbine

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#64]
Bad friendly text for laser carbine
![](https://cdn.discordapp.com/attachments/379026544296853506/393113015085694976/20171220104643_1.jpg)

**Comment by Karnich** [comment]
this is not just laser its all except CV.. working on it

**Comment by Karnich** [comment]
how do we wanna arrange the localization files? its weird that we have an SMGs folder with texts for MR, BR and SMG, but only for CV, BG and BM because the 2 other tiers are in the Lasers and Coils folder...

**Comment by Danice123** [comment]
Feel free to reorganize it

**Comment by Karnich** [comment]
so.. tiers or per weapon? ;)

**Comment by Danice123** [comment]
Up to you. Whatever you think makes the most sense
