### ISSUE TITLE
Conflicts with Perk Pack and Weapons pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#65]
~New classes in the perk pack conflict with the weapons pack and prevent equipping valid weapons~
~in case you didn't see the clarification this isn't as severe as the issue you opened for it - the perk pack grenadier isn't supposed to be able to equip those, it's just a display issue.
Checking with the classes turned off proper now
The fix will probably be removing the default soldier classes in perk pack
[XComGame.X2SoldierClass_DefaultClasses]
-SoldierClasses="Grenadier"
-SoldierClasses="Specialist"
-SoldierClasses="Ranger"
-SoldierClasses="Sharpshooter"~

Either way though, I think the way to go is to just change "m_strNeedsSoldierClass=<XGParam:StrValue0/!SoldierClassName/> ONLY" in the localization file to something more catch-all - several classes in LWPP share weapon types, so saying 'ONLY' on them is wrong one way or another.

![](https://cdn.discordapp.com/attachments/379026544296853506/393118201309036547/20171220140702_1.jpg)

**Comment by Karnich** [comment]
i have fixed this on my Technical_playground_modbuddy branch on the Perks pack. Hoping to get it merged when @Favid is back

**Comment by Karnich** [comment]
this should be fixed by now
