### ISSUE TITLE
Add LMG to weapons pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#7]
Note: LMG has squadsight ability, so this may be slightly more complex than other weapons. See the SMG implementation in mod.
Add LMG to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by Karnich** [comment]
looking for a first issue to take ;) so this seems to be the only one? ;D

**Comment by TNychka** [comment]
Depends on how much experience you have, I think the other ones are very doable if you have any experience with xcom 2 modding. If you're looking to learn this is a good one to take though. Do you want to take this issue?

**Comment by Karnich** [comment]
i tried making a red fog mod when xcom 2 just released... so i only have a feint memory of it ;) Ill take this issue.

**Comment by TNychka** [comment]
It's yours then. Any questions just let me know.

**Comment by TNychka** [comment]
~@Karnich how is the issue going? Are you still working on it?~ I see progress on the fork, all good. Continue as before.
