### ISSUE TITLE
Port the LW2 Technical Gauntlet

### ISSUE THREAD

**Issue by Karnich** [X2LongWarOfTheChosen/LWOTC_WeaponPack#75]

**Comment by Karnich** [comment]
@Favid have done some work on this but is waiting on some highlander changes to make FX work

**Comment by Danice123** [comment]
Is this gonna depend on highlander when the gauntlet is added?

**Comment by Karnich** [comment]
I think it will.. but we dont know yet, if its going to be added to this pack or the Perks pack
