### ISSUE TITLE
Add SAWs to the weapons pack

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#8]
Add SAWs to the pack for Conventional, Laser, Magnetic, Coil, Beam tier.
This will include adding the assets from RealityMachina and Uejii's pack, setting the research requirements, setting the engineering costs, and setting the abilities.
See for more information including stats: https://docs.google.com/document/d/1twloedm2C8Xr8DM5OHTE_VrVs_7Gt8td1rRkIu63Whw/edit

**Comment by Pete-Hamlin** [comment]
I can take this one

**Comment by TNychka** [comment]
Sounds good, it's yours. The assets come from Uejii's weapon pack and realitymachina's LW2 expansion of that.

**Comment by TNychka** [comment]
@Pete-Hamlin how is the issue going? Are you still working on it?

**Comment by Pete-Hamlin** [comment]
Hi, sorry for the lack of update on work, past 2 weeks have been utterly mental with university deadlines, so not had much time to work on the issue. Christmas break begins on Friday, so hoping to be able to get to work properly on it then.

So yeah, not had a lot of time so far, by should be good over the next few weeks to get this done, and hopefully have a look at a few others.

**Comment by TNychka** [comment]
Yeah not a problem, just making sure!

**Comment by Danice123** [comment]
#59
