### ISSUE TITLE
New weapon attachments

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_WeaponPack#83]
what id like to do for them is to have a seperate version of the current upgrades for each of the different Attachment Classes you can see on the left, but without the Basic-Advanced-Superior progression. So at example for Scopes you would have Scope_Assault, Scope_Combat, Scope_Precision, Scope_Heavy, Scope_Shotgun. https://docs.google.com/spreadsheets/d/1m__UMMaZbcTTeq9TZOe_nfKHq9HpYD-puT17-_ni_Ng/edit#gid=0

**Comment by TNychka** [comment]
Run this by Chris the Thin Mint if you need more information

**Comment by ChrisTheThinMint** [comment]
The attachment classes that quote refers to can be be seen in the new weapon design sheet. https://docs.google.com/spreadsheets/d/1m__UMMaZbcTTeq9TZOe_nfKHq9HpYD-puT17-_ni_Ng/edit#gid=0

The current ones are: Assault, Combat, Heavy, Precision and Shotgun. One or two more may come in the future.
